name: PHPCS

on: [push, pull_request]

jobs:
  run:
    name: PHPCS ${{ matrix.php-version }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.1', '8.2', '8.3']

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring

      - uses: actions/checkout@master

      - run: composer validate --strict
      - run: composer install
      - run: composer require squizlabs/php_codesniffer
      - run: composer audit
      - run: vendor/bin/phpcs -p --colors --extensions=php --standard=PSR12 src tests